version: "3.3"

services:


  db:
    image: 'postgres:16.3-alpine'
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - /home/database-mount/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    expose:
      - "5433"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  java-app:
    container_name: java-app
    build:
      context: ./backend/food-making-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    ports:
      - "8080:8080"




  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    env_file:
      - ./frontend/.env

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/database-mount/pgdata
  swagger-ui:
    external: false

